mysite/mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/todo/')),
]

mysite/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:id>/delete', views.delete, name='delete'),
]

mysite/todo/models.py
from django.db import models


class Post(models.Model):
    body = models.CharField(max_length=200)
    text = models.CharField(max_length=200)

mysite/todo/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body','text')

mysite/todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Post
from .forms import PostForm

# Create your views here.
def index(request):
    posts = Post.objects.all()
    form = PostForm()
    context = {'posts': posts, 'form': form, }
    return render(request, 'todo/index.html', context)
    
def create(request):
    form = PostForm(request.POST)
    form.save(commit=True)
    return HttpResponseRedirect(reverse('todo:index'))

def delete(request, id=None):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return HttpResponseRedirect(reverse('todo:index'))

mysite/todo/templates/todo/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Todo List</title>
        <!-- CSS And JavaScript -->
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
        <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
        <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
        <link rel="stylesheet" href="{% static 'css/todo.css' %}">
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

mysite/todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
    <body style="background-color:LightGreen;">
    <div class="page-header" style="background-color:Lime;margin: 0 auto;"><h1>Movie Reviews Blog</h1></div>
    <img src="https://www.screengeek.net/wp-content/uploads/2018/09/superman-henry-cavill-1.jpg" alt="Flowers in Chania">
    <br>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'todo:create' %}" method="post" >
        {% csrf_token %}
        <!-- Post Name -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6" style="margin: 0 auto; width: 180px;">
                <h2 >Movie Post </h2>
            </div>
            
            <div class="col-sm-6"  style="">
                Movie-Name:
                {{ form.body }}
                Review:
                {{ form.text }}
            </div>
        </div>

        <!-- Add Post Button -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6" style="margin: 0 auto; width: 180px;">
                <button type="submit" class="btn btn-default" style="background-color:Lime;">
                    <i class="fa fa-plus"></i> Add New Post
                </button>
            </div>
        </div>

    </form>
    <br>

    <!-- Current Feed -->
    <h2>Posts Feed</h2>
    <table class="table table-striped todo-table">
        <tbody>
            {% for post in posts %}
                <tr>
                    <!-- Post Name -->
                    <td>
                        <div>Movie-Name:  {{ post.body }}</div>
                        <div>{{ post.text }}</div>
                    </td>
                    
                    <td>
                        <form action="{% url 'todo:delete' post.id %}" method="post">
                            {% csrf_token %}
                            <button>Delete Post</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </body>
    
    
{% endblock %}